export interface Course {
  id: string;
  title: string;
  category: string;
  categorySlug: 'language-tests' | 'competitive-exams' | 'foreign-languages' | 'skill-catalyst';
  packType: 'Champion Pack' | 'Champion Pack +' | 'Self Preparation Pack' | 'Live Class' | 'Multi-Level Pack';
  tagline: string;
  features: string[];
  duration: string;
  mode: 'Live + Portal' | 'Self-Paced' | 'Live Interactive' | 'Comprehensive Pathway';
  level: string;
  badgeColor?: string;
  popular?: boolean;
}

export const COURSE_CATEGORIES = [
  { id: 'all', label: 'All Programs', count: 24 },
  { id: 'language-tests', label: 'Language Tests (IELTS / PTE / DET)', count: 9 },
  { id: 'competitive-exams', label: 'Competitive (SAT / GRE / GMAT)', count: 7 },
  { id: 'foreign-languages', label: 'German & French', count: 4 },
  { id: 'skill-catalyst', label: 'Skill Catalyst & Career', count: 4 },
] as const;

export const COURSES_DATA: Course[] = [
  // IELTS
  {
    id: 'ielts-academic-champion',
    title: 'IELTS Academic',
    category: 'IELTS Academic',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Build academic English with structured practice, feedback, and IELTS aligned mock tests.',
    features: ['Live Interactive Sessions', 'Official Cambridge Mock Simulations', 'Daily Writing & Speaking Assessments', 'Student Learning Dashboard'],
    duration: '6-8 Weeks',
    mode: 'Live + Portal',
    level: 'Beginner to Advanced',
    popular: true,
  },
  {
    id: 'ielts-academic-champion-plus',
    title: 'IELTS Academic',
    category: 'IELTS Academic',
    categorySlug: 'language-tests',
    packType: 'Champion Pack +',
    tagline: 'Build academic English with structured practice, feedback, and IELTS aligned mock tests.',
    features: ['1-on-1 Speaking Mock Interviews', 'Personalized Band Score Roadmap', 'Priority Essay Corrections in 24h', 'Exclusive Visa & Admission Session'],
    duration: '8-10 Weeks',
    mode: 'Live Interactive',
    level: 'All Levels',
    popular: true,
  },
  {
    id: 'ielts-academic-self-prep',
    title: 'IELTS Academic',
    category: 'IELTS Academic',
    categorySlug: 'language-tests',
    packType: 'Self Preparation Pack',
    tagline: 'Build academic English with structured practice, feedback, and IELTS aligned mock tests.',
    features: ['Full Video Course Access', '100+ Practice Question Banks', 'Self-Paced Mock Tests', 'Downloadable Cheat Sheets'],
    duration: 'Self-Paced (6 Months Access)',
    mode: 'Self-Paced',
    level: 'Intermediate',
  },
  {
    id: 'ielts-general-champion',
    title: 'IELTS General',
    category: 'IELTS General',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Sharpen everyday English for work, migration, and communication through focused practice.',
    features: ['CLB 9/10 Targeted Training', 'Letter Writing & Reading Drills', 'Live Speaking Club Practice', 'Express Entry Consultation Included'],
    duration: '6 Weeks',
    mode: 'Live + Portal',
    level: 'All Levels',
    popular: true,
  },
  {
    id: 'ielts-general-self-prep',
    title: 'IELTS General',
    category: 'IELTS General',
    categorySlug: 'language-tests',
    packType: 'Self Preparation Pack',
    tagline: 'Sharpen everyday English for work, migration, and communication through focused practice.',
    features: ['Recorded Grammar & Module Videos', 'Timed Mock Test Software', 'Real Exam Task 1 & 2 Samples', '24/7 Portal Access'],
    duration: 'Self-Paced (6 Months)',
    mode: 'Self-Paced',
    level: 'Working Professionals',
  },

  // PTE
  {
    id: 'pte-academic-champion',
    title: 'PTE Academic',
    category: 'PTE Academic',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Master computer-based English with timed practice, feedback, and every exam-focused strategy.',
    features: ['Pearson AI Scoring Simulator', 'Proven Templates for Essay & SST', 'Repeat Sentence & DI Mastery', 'Weekly Performance Analytics'],
    duration: '4-6 Weeks',
    mode: 'Live + Portal',
    level: 'All Levels',
    popular: true,
  },
  {
    id: 'pte-academic-live',
    title: 'PTE Academic',
    category: 'PTE Academic',
    categorySlug: 'language-tests',
    packType: 'Live Class',
    tagline: 'Master computer-based English with timed practice, feedback, and every exam-focused strategy.',
    features: ['Small Batch Live Classes', 'Daily Speaking & Pronunciation Coaching', 'Real Exam Question Predictions', 'Direct Trainer Q&A'],
    duration: '4 Weeks',
    mode: 'Live Interactive',
    level: 'Target 65-79+',
  },
  {
    id: 'pte-academic-self-prep',
    title: 'PTE Academic',
    category: 'PTE Academic',
    categorySlug: 'language-tests',
    packType: 'Self Preparation Pack',
    tagline: 'Master computer-based English with timed practice, feedback, and every exam-focused strategy.',
    features: ['AI-Powered Test Software', '30 Full Length Mock Tests', 'Pronunciation & Pitch Feedback', 'Sectional Speed Drills'],
    duration: 'Self-Paced (3-6 Months)',
    mode: 'Self-Paced',
    level: 'Beginner to Advanced',
  },
  {
    id: 'pte-core-champion',
    title: 'PTE Core',
    category: 'PTE Core',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Prepare practical English skills for Canadian pathways through focused, structured practice.',
    features: ['Updated PTE Core Exam Syllabus', 'Email Writing & Vocational Speaking', 'Full Sectional Mocks', 'Canada PR Point Boost Tips'],
    duration: '4 Weeks',
    mode: 'Live + Portal',
    level: 'Canada PR Aspirants',
  },

  // CELPIP
  {
    id: 'celpip-champion',
    title: 'CELPIP Preparation',
    category: 'CELPIP',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Strengthen practical English for Canada with targeted practice and test strategies.',
    features: ['Canadian Accent Listening Modules', 'Survey Response Writing Drills', 'Timed Mock Test Portal', '1-on-1 Speaking Evaluation'],
    duration: '5 Weeks',
    mode: 'Live + Portal',
    level: 'Canada Immigration',
    popular: true,
  },
  {
    id: 'celpip-self-prep',
    title: 'CELPIP Preparation',
    category: 'CELPIP',
    categorySlug: 'language-tests',
    packType: 'Self Preparation Pack',
    tagline: 'Strengthen practical English for Canada with targeted practice and test strategies.',
    features: ['Interactive Reading & Listening Modules', 'Model Speaking Audio Answers', 'Task 1 & Task 2 Writing Samples', 'Mock Exam Simulator'],
    duration: 'Self-Paced (4 Months)',
    mode: 'Self-Paced',
    level: 'All Levels',
  },

  // Duolingo & TOEFL
  {
    id: 'duolingo-champion',
    title: 'Duolingo English Test',
    category: 'Duolingo',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Prepare flexibly with focused practice for the fully online English test.',
    features: ['Adaptive Subscore Strategies', 'Interactive Reading & Writing Hacks', '15 Full-length Mock Tests', 'Fast Results in 48h Prep Plan'],
    duration: '3-4 Weeks',
    mode: 'Live + Portal',
    level: 'Undergrad & Masters',
  },
  {
    id: 'toefl-live-class',
    title: 'TOEFL Preparation',
    category: 'TOEFL',
    categorySlug: 'language-tests',
    packType: 'Live Class',
    tagline: 'Build academic English skills with targeted practice across every tested section.',
    features: ['Academic Reading Passages Mastery', 'Integrated Writing Workshops', 'Live Speech Clarity Sessions', 'Official ETS Pattern Mocks'],
    duration: '6 Weeks',
    mode: 'Live Interactive',
    level: 'Advanced',
  },

  // Spoken English
  {
    id: 'spoken-english-champion',
    title: 'Spoken English',
    category: 'Spoken English',
    categorySlug: 'language-tests',
    packType: 'Champion Pack',
    tagline: 'Improve everyday English fluency through guided speaking practice, feedback, and assignments.',
    features: ['Daily Conversation Clubs', 'Accent & Neutralization Drills', 'Business & Social Vocabulary', 'Personalized Confidence Building'],
    duration: '8 Weeks',
    mode: 'Live Interactive',
    level: 'Beginner to Fluent',
  },

  // Competitive Exams: SAT
  {
    id: 'dsat-champion',
    title: 'SAT Preparation',
    category: 'D-SAT',
    categorySlug: 'competitive-exams',
    packType: 'Champion Pack',
    tagline: 'Build stronger scores through focused concepts, timed practice, and detailed analysis.',
    features: ['Desmos Calculator Speed Hacks', 'Adaptive Math Module Training', 'Hard Reading & Writing Drills', '8 Full Bluebook Style Mocks'],
    duration: '8-10 Weeks',
    mode: 'Live + Portal',
    level: 'High School Students',
    popular: true,
  },
  {
    id: 'dsat-live-class',
    title: 'SAT Preparation',
    category: 'D-SAT',
    categorySlug: 'competitive-exams',
    packType: 'Live Class',
    tagline: 'Build stronger scores through focused concepts, timed practice, and detailed analysis.',
    features: ['Concept Masterclasses', 'Live Step-by-Step Problem Solving', 'Weekly Doubt Clinics', 'College Board Question Drills'],
    duration: '8 Weeks',
    mode: 'Live Interactive',
    level: 'Target 1400-1550+',
  },
  {
    id: 'dsat-self-prep',
    title: 'SAT Preparation',
    category: 'D-SAT',
    categorySlug: 'competitive-exams',
    packType: 'Self Preparation Pack',
    tagline: 'Build stronger scores through focused concepts, timed practice, and detailed analysis.',
    features: ['500+ Video Solutions', 'Adaptive Topic Quizzes', 'Sectional Speed Tests', 'Formula Sheets & Cheatsheets'],
    duration: 'Self-Paced (6 Months)',
    mode: 'Self-Paced',
    level: 'Self-Study Students',
  },

  // GRE
  {
    id: 'gre-champion',
    title: 'GRE Preparation',
    category: 'GRE',
    categorySlug: 'competitive-exams',
    packType: 'Champion Pack',
    tagline: 'Sharpen Quant and Verbal performance through targeted practice and analytical strategy.',
    features: ['1000+ High-Frequency Word Roots', 'Quant Advanced Shortcuts & Traps', 'AWA Analytical Essay Feedback', '6 Full Shorter GRE Mocks'],
    duration: '8-10 Weeks',
    mode: 'Live + Portal',
    level: 'Graduate Aspirants',
    popular: true,
  },
  {
    id: 'gre-live-class',
    title: 'GRE Preparation',
    category: 'GRE',
    categorySlug: 'competitive-exams',
    packType: 'Live Class',
    tagline: 'Sharpen Quant and Verbal performance through targeted practice and analytical strategy.',
    features: ['Live Batch with Top Trainers', 'Sentence Equivalence Tricks', 'Quant Trap Analysis', 'Personalized Mentorship'],
    duration: '8 Weeks',
    mode: 'Live Interactive',
    level: 'Target 320+',
  },
  {
    id: 'gre-self-prep',
    title: 'GRE Preparation',
    category: 'GRE',
    categorySlug: 'competitive-exams',
    packType: 'Self Preparation Pack',
    tagline: 'Sharpen Quant and Verbal performance through targeted practice and analytical strategy.',
    features: ['Shorter GRE Pattern Mocks', 'Vocab Flashcard App Access', 'Video Solutions for Hard Questions', 'Progress Analytics Dashboard'],
    duration: 'Self-Paced (6 Months)',
    mode: 'Self-Paced',
    level: 'Self Learners',
  },

  // GMAT
  {
    id: 'gmat-live-class',
    title: 'GMAT Preparation',
    category: 'GMAT',
    categorySlug: 'competitive-exams',
    packType: 'Live Class',
    tagline: 'Strengthen business-school readiness with focused Quant, Verbal, and Data practice skills.',
    features: ['Data Insights Real-World Case Prep', 'Critical Reasoning Frameworks', 'Quant Concept Mastery', 'Official Mock Test Strategy'],
    duration: '10 Weeks',
    mode: 'Live Interactive',
    level: 'MBA Aspirants',
    popular: true,
  },

  // Foreign Languages: German
  {
    id: 'german-basic-a1',
    title: 'German Preparation',
    category: 'German',
    categorySlug: 'foreign-languages',
    packType: 'Champion Pack',
    tagline: 'Develop practical German for study, university applications, and everyday communication confidently.',
    features: ['Goethe A1 Exam Syllabus', 'Live Pronunciation & Speaking', 'Grammar & Case System (Nom/Akk/Dat)', 'Goethe Exam Model Papers'],
    duration: '6-8 Weeks',
    mode: 'Live + Portal',
    level: 'Level A1 (Beginner)',
    popular: true,
  },
  {
    id: 'german-a1-a2-b1',
    title: 'German Preparation',
    category: 'German',
    categorySlug: 'foreign-languages',
    packType: 'Multi-Level Pack',
    tagline: 'Develop practical German for study, university applications, and everyday communication confidently.',
    features: ['Complete A1 + A2 + B1 Curriculum', 'Ausbildung & University Consulting', 'Fluency & Conversation Clubs', 'Goethe / telc Exam Training'],
    duration: '5-6 Months',
    mode: 'Comprehensive Pathway',
    level: 'Levels A1, A2 & B1',
  },

  // Foreign Languages: French
  {
    id: 'french-basic-a1-a2',
    title: 'French Preparation',
    category: 'French',
    categorySlug: 'foreign-languages',
    packType: 'Multi-Level Pack',
    tagline: 'Build practical French for study, work, communication, and Canadian pathways abroad.',
    features: ['DELF Format Training', 'Interactive Speaking Immersion', 'French Grammar & Conjugations', 'Cultural & Communication Context'],
    duration: '12 Weeks',
    mode: 'Live + Portal',
    level: 'Levels A1 & A2',
  },
  {
    id: 'french-b1-b2-tef',
    title: 'French Preparation',
    category: 'French',
    categorySlug: 'foreign-languages',
    packType: 'Champion Pack',
    tagline: 'Build practical French for study, work, communication, and Canadian pathways abroad.',
    features: ['TEF & TCF Canada Focused Syllabus', 'Intensive Sectional Drills', 'Express Entry CRS Score Optimization', 'Expert Bilingual Trainers'],
    duration: '16-20 Weeks',
    mode: 'Comprehensive Pathway',
    level: 'B1, B2 & TEF',
    popular: true,
  },

  // Skill Catalyst
  {
    id: 'skill-catalyst-combo',
    title: 'Skill Catalyst Combo Pack',
    category: 'Skill Catalyst',
    categorySlug: 'skill-catalyst',
    packType: 'Champion Pack',
    tagline: 'The ultimate professional readiness suite: Career, Google Suite, and Modern Business Tech.',
    features: ['Resume & LinkedIn Optimization', 'Google Workspace Mastery', 'Productivity & AI Tools for Office', 'Mock HR & Technical Interviews'],
    duration: '6 Weeks',
    mode: 'Live + Portal',
    level: 'Graduates & Professionals',
    popular: true,
  },
  {
    id: 'skill-catalyst-career-essentials',
    title: 'Career Essentials',
    category: 'Skill Catalyst',
    categorySlug: 'skill-catalyst',
    packType: 'Live Class',
    tagline: 'Build workplace-ready skills for internships, applications, communication, and professional confidence readiness.',
    features: ['ATS Resume Builder', 'Behavioral Interview STAR Technique', 'Executive Email Writing', 'Salary Negotiation Coaching'],
    duration: '4 Weeks',
    mode: 'Live Interactive',
    level: 'Job Seekers',
  },
  {
    id: 'skill-catalyst-gsuite',
    title: 'Google Suite Hub',
    category: 'Skill Catalyst',
    categorySlug: 'skill-catalyst',
    packType: 'Self Preparation Pack',
    tagline: 'Master everyday Google tools for smoother, faster, more organised workplace productivity.',
    features: ['Advanced Sheets Formulas & Dashboards', 'Professional Presentation Design', 'Cloud Collaboration Mastery', 'Practical Business Templates'],
    duration: 'Self-Paced (Lifetime Access)',
    mode: 'Self-Paced',
    level: 'All Levels',
  },
  {
    id: 'skill-catalyst-bizz-tech',
    title: 'BizzTech',
    category: 'Skill Catalyst',
    categorySlug: 'skill-catalyst',
    packType: 'Live Class',
    tagline: 'Learn practical business and digital tools through focused, hands-on skill building.',
    features: ['AI Workplace Tools (ChatGPT, Claude)', 'Project Management (Notion, Trello)', 'Data Visualization Basics', 'Automation Workflows'],
    duration: '4 Weeks',
    mode: 'Live Interactive',
    level: 'All Levels',
  },
];
